/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author Anonymous
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnFRecursivo = new javax.swing.JButton();
        btnFMemoized = new javax.swing.JButton();
        btnFButtonUp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 255, 102));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Fibonacci CS Dojo.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        btnFRecursivo.setForeground(new java.awt.Color(0, 0, 0));
        btnFRecursivo.setText("FibonacciRecursivo");
        btnFRecursivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFRecursivoActionPerformed(evt);
            }
        });

        btnFMemoized.setForeground(new java.awt.Color(0, 0, 0));
        btnFMemoized.setText("Fibonacci con Memoized");
        btnFMemoized.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFMemoizedActionPerformed(evt);
            }
        });

        btnFButtonUp.setForeground(new java.awt.Color(0, 0, 0));
        btnFButtonUp.setText("Fibonacci con Button-up");
        btnFButtonUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFButtonUpActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingresa el numero a obtener: ");

        txtNumero.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnFRecursivo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnFMemoized)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(btnFButtonUp)
                        .addGap(58, 58, 58))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFRecursivo)
                    .addComponent(btnFMemoized)
                    .addComponent(btnFButtonUp))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFRecursivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFRecursivoActionPerformed
     pila = new java.util.Stack<>();
    
        int posicion = Integer.parseInt(txtNumero.getText());
        int valor = Fibonacci(posicion);
        JOptionPane.showMessageDialog(this, "El Fibonacci de "
                +posicion+" es "+valor);
    }//GEN-LAST:event_btnFRecursivoActionPerformed

    private void btnFMemoizedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFMemoizedActionPerformed
        pila = new java.util.Stack<>();
        int posicion = Integer.parseInt(txtNumero.getText());
         int valor = fibonacciMemoized(posicion,null);
         
         JOptionPane.showMessageDialog(this, "El Fibonacci de "
                +posicion+" es "+valor);

     
    }//GEN-LAST:event_btnFMemoizedActionPerformed
  
    
    private void btnFButtonUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFButtonUpActionPerformed
         pila = new java.util.Stack<>();
        int posicion = Integer.parseInt(txtNumero.getText());
         int valor = fibBottomUp(posicion,null);
         
         JOptionPane.showMessageDialog(this, "El Fibonacci de "
                +posicion+" es "+valor);
     
  
    }//GEN-LAST:event_btnFButtonUpActionPerformed
      private java.util.Stack<Integer> pila = new java.util.Stack();
    private int Fibonacci(int posicion){
        posicion = java.lang.Math.abs(posicion);
        if(posicion < 2) return posicion;
        else{
            int respuesta = Fibonacci(posicion - 1) + Fibonacci(posicion - 2);
            pila.push(respuesta);
            return respuesta;
        }
        
    }  
    int result;

    private int fibonacciMemoized(int posicion, int [] mem ){
       int[]memo= new int[posicion+1];
       
  if(memo[(int)posicion]!=0){
   return memo[(int)posicion];
  
    }else if(posicion ==1 || posicion==2){
    result = 1;
    } else {
    result = fibonacciMemoized(posicion-1,mem) + fibonacciMemoized(posicion-2,mem);
    memo[posicion]=result;
    }
    return result;
   
    }
    private int fibBottomUp(int posicion,int []m){
       int[]bottomUp= new int[posicion+1];
          posicion = java.lang.Math.abs(posicion);
       if(posicion ==1 || posicion==2) return 1;
       {
   bottomUp[posicion]= bottomUp[(int)posicion]=0 * (posicion + 1);
    bottomUp[1] =1;
    bottomUp[2] =2;
    
       }
    for(int i = 2; i<=(posicion); i++){
    bottomUp[i] = bottomUp[i - 1] + bottomUp[i - 2]; 
     }
        return bottomUp[posicion];
     
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFButtonUp;
    private javax.swing.JButton btnFMemoized;
    private javax.swing.JButton btnFRecursivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
